version: '3.8'

services:
  postgres-auth:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    networks:
      - rede

  postgres-payment:
    image: postgres:latest
    container_name: postgres-payment
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon
    ports:
      - "5434:5434"
    volumes:
      - postgres_data_payment:/var/lib/postgresql/data
    networks:
      - rede

  hackathonauth:
    image: emerlopes95/hackathonauth:latest
    container_name: hackathonauth
    ports:
      - "8080:8080"
    depends_on:
      - postgres-auth
    networks:
      - rede

  hackathon-payments:
    image: emerlopes95/hackathon-payments:latest
    container_name: hackathon-payments
    ports:
      - "8081:8081"
    depends_on:
      - postgres-payment
    networks:
      - rede

volumes:
  postgres_data_auth:
  postgres_data_payment:

networks:
  rede:
    driver: bridge
