version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede

  hackathonauth:
    image: emerlopes95/hackathonauth:latest
    container_name: hackathonauth
    ports:
      - "8085:8085"
    networks:
      - rede

  creditlimitchecker:
    image: emerlopes95/creditlimitchecker:latest
    container_name: creditlimitchecker
    ports:
      - "8086:8086"
    networks:
      - rede

volumes:
  postgres_data:

networks:
  rede:
    driver: bridge
